name: Conda solo

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}

    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        with:
          activate-environment: conda-env
          environment-file: environment.yml
          python-version: 3.8
          auto-activate-base: false
          channels: conda-forge, defaults
          use-only-tar-bz2: true