name: Mamba solo

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}

    steps:
      - uses: actions/checkout@v3
      - name: Cache conda
        uses: actions/cache@v2
        env:
          # Increase this value to reset cache if environment.yml has not changed
          CACHE_NUMBER: 0
        with:
          path: ~/conda_pkgs_dir
          key:
            ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{
            hashFiles('environment.yml') }}
      - uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          activate-environment: mamba-cache-env
          environment-file: environment.yml
          channel-priority: strict
          auto-activate-base: false
          python-version: 3.8
          channels: conda-forge,defaults,pytorch